/**
 * Central business configuration.
 *
 * ────────────────────────────────────────────────────────────────
 * THIS IS THE ONLY FILE YOU NEED TO EDIT FOR BUSINESS DETAILS.
 * Every component reads from here, so nothing is hardcoded elsewhere.
 * Values marked TODO are placeholders and must be replaced before launch.
 * ────────────────────────────────────────────────────────────────
 */

export const siteConfig = {
  // ---- Brand -------------------------------------------------------------
  /** TODO: replace with your final registered business name. */
  name: "EverInvite Studio",
  /** Used in tight spaces such as the mobile header and the footer mark. */
  shortName: "EverInvite",
  tagline: "Beautiful web invitations for unforgettable celebrations.",
  description:
    "We design interactive web invitations for weddings, engagements, homecomings, birthdays and celebrations of every kind. One link, opened on any phone, remembered long after the day.",

  // ---- Contact -----------------------------------------------------------
  /** Full international form. Drives every wa.me link on the site. */
  whatsappNumber: "+94 77 343 0233",
  /** The number customers call. Same line as WhatsApp. */
  phone: "+94 77 343 0233",
  /** Business email, shown on the contact page and used as the mailto fallback. */
  email: "flowercartdecos@gmail.com",

  // ---- Social ------------------------------------------------------------
  // Set a value to an empty string to hide that link. Instagram and TikTok
  // stay empty until those accounts are live.
  instagram: "",
  facebook: "https://www.facebook.com/share/1Hup8fdPGF/",
  tiktok: "",

  // ---- Where and when ----------------------------------------------------
  /** TODO: adjust if you want a more specific city or district. */
  location: "Colombo, Sri Lanka",
  servingNote: "Working with couples across Sri Lanka and overseas.",
  workingHours: "Monday to Saturday, 9.00 am to 7.00 pm (Sri Lanka time)",
  /** Currency used when you publish package prices. */
  currency: "LKR",

  // ---- Deployment --------------------------------------------------------
  /**
   * TODO: set this to your live domain once the site is deployed.
   * Used for canonical URLs, sitemap entries and social preview images.
   * No trailing slash.
   */
  siteUrl: "https://ever-invite-studio.vercel.app",

  // ---- SEO ---------------------------------------------------------------
  seo: {
    title: "Digital Wedding Invitations in Sri Lanka | EverInvite Studio",
    description:
      "Custom interactive web invitations for weddings and celebrations in Sri Lanka. Share one link, and your guests open a designed invitation with venue details, countdown and RSVP.",
    keywords: [
      "digital wedding invitations Sri Lanka",
      "web invitations Sri Lanka",
      "online wedding invitation",
      "interactive digital invitation",
      "custom wedding invitation website",
      "digital event invitation",
    ],
    /**
     * Social sharing image. Generated by src/app/opengraph-image.tsx, so it
     * updates automatically when the brand name or tagline changes.
     * Replace with a path under /public if you would rather use your own file.
     */
    ogImage: "/opengraph-image",
  },
} as const;

export type SiteConfig = typeof siteConfig;

/**
 * True once a real WhatsApp number has been configured above.
 * While the placeholder is in place the site quietly prefers email so that
 * visitors never land on a broken WhatsApp link.
 */
export function hasWhatsApp(): boolean {
  return /^\+?\d{9,15}$/.test(siteConfig.whatsappNumber.replace(/[\s-]/g, ""));
}

/** Digits-only form of the WhatsApp number, which is what wa.me expects. */
export function whatsAppDigits(): string {
  return siteConfig.whatsappNumber.replace(/\D/g, "");
}
